In [1]:
#numpy

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[1]

2

In [6]:
a[-1]

3

In [12]:
a[:]

array([1, 2, 3])

In [10]:
a[:2]

array([1, 2])

In [11]:
a[:-1]

array([1, 2])

In [13]:
a.shape

(3,)

In [14]:
a.ndim

1

In [19]:
 b=np.array([['a','b','c'],['d','e','f'],['g','h','i']])

In [20]:
b

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [21]:
b.shape

(3, 3)

In [22]:
b.size

9

In [23]:
b[:]

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [24]:
b[1]

array(['d', 'e', 'f'], dtype='<U1')

In [33]:
b[1:3]

array([['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [78]:
b[[1,0]]

array([['d', 'e', 'f'],
       ['a', 'b', 'c']], dtype='<U1')

In [36]:
b[1][1:4]

array(['e', 'f'], dtype='<U1')

In [49]:
b[:,:2]
  

array([['a', 'b'],
       ['d', 'e'],
       ['g', 'h']], dtype='<U1')

In [52]:
b[1,2]

'f'

In [54]:
b[:,:1]

array([['a'],
       ['d'],
       ['g']], dtype='<U1')

In [57]:
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [58]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
c.mean()

6.5

In [61]:
c.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [62]:
c.mean(axis=0)

array([5., 6., 7., 8.])

In [63]:
c.std()

3.452052529534663

In [64]:
c.var()

11.916666666666666

In [66]:
c.sum(axis=1)

array([10, 26, 42])

In [67]:
d=np.arange(5)

In [68]:
d

array([0, 1, 2, 3, 4])

In [69]:
d+20

array([20, 21, 22, 23, 24])

In [71]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
d*10

array([ 0, 10, 20, 30, 40])

In [73]:
d+10

array([10, 11, 12, 13, 14])

In [100]:
e=np.array([10,20,30,40,50])

In [101]:
e[[1,4]]

array([20, 50])

In [91]:
e[1],e[4]

(20, 50)

In [93]:
e[[False,True,False,False,True]]

array([20, 50])

In [96]:
e<=30

array([ True,  True,  True, False, False])

In [103]:
e[e<=30]

array([10, 20, 30])

In [114]:
e[(e<=30) | (e>=50)]

array([10, 20, 30, 50])

In [115]:
e[(e>=30)&(e<=50)]

array([30, 40, 50])

In [118]:
r=np.random.randint(100,size=[3,3])

In [119]:
r

array([[ 9, 27, 77],
       [77, 60,  8],
       [57, 76, 39]])

In [121]:
r<40

array([[ True,  True, False],
       [False, False,  True],
       [False, False,  True]])

In [122]:
r[r<40]

array([ 9, 27,  8, 39])

In [123]:
3**2

9

In [124]:
3*2

6

In [125]:
2**2

4

In [126]:
2**5

32

In [127]:
2*5

10

In [147]:
x=1
while x<5:
    print('Inner',x)
    x*=2
    print('outer',x)

Inner 1
outer 2
Inner 2
outer 4
Inner 4
outer 8


In [ ]:
a =[1,2,3,4,5]
x=1
while x>len(a):
    print(a)