In [22]:
import numpy as np

In [2]:
l=[1,2,3,45,5]

In [3]:
l

[1, 2, 3, 45, 5]

In [4]:
l1=[1,2,3,4,5,6,"priya"]

In [5]:
l1

[1, 2, 3, 4, 5, 6, 'priya']

In [6]:
type(l1)

list

In [7]:
type(np.array(l1))

numpy.ndarray

In [8]:
np.array([[1,2,34]])

array([[ 1,  2, 34]])

In [9]:
np.array([1,2,3,4,5],ndmin=4) #ndmin will give u n dimensional array


array([[[[1, 2, 3, 4, 5]]]])

In [10]:
np.mat([1,2,3,4,5,6,7,8])

matrix([[1, 2, 3, 4, 5, 6, 7, 8]])

In [11]:
arr=np.array(['a','b','c','d','e'])

In [12]:
arr[1]

'b'

In [13]:
arr[0:3]

array(['a', 'b', 'c'], dtype='<U1')

In [14]:
arr[0:5:2]

array(['a', 'c', 'e'], dtype='<U1')

In [15]:
ar=np.array([[2,3],[4,6]])

In [16]:
ar

array([[2, 3],
       [4, 6]])

In [17]:
ar[0]

array([2, 3])

In [18]:
ar[0][1]

3

In [19]:
ba=np.array([[4,5],[64,8],[24,99]])

In [20]:
ba

array([[ 4,  5],
       [64,  8],
       [24, 99]])

In [21]:
ba[2][1]

99

In [22]:
ba[2,1]

99

In [23]:
np.asarray([1,2,3,5])

array([1, 2, 3, 5])

In [24]:
np.asarray([4,5,6,7],dtype=np.float64)

array([4., 5., 6., 7.])

In [25]:
np.asanyarray([3,468,46,8]) ## asanyarray will convert anyform data to array

array([  3, 468,  46,   8])

In [26]:
np.asanyarray(np.mat([1,3,46]))

matrix([[ 1,  3, 46]])

In [27]:
np.fromfunction(lambda x,y :x+y,(3,3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [17]:
t=lambda x,y,z:(x<y) & (x<z)

In [18]:
t(2,3,5)

True

In [28]:
np.fromfunction(lambda i,j,k:i+j+k, (3,3,1),dtype=int)

array([[[0],
        [1],
        [2]],

       [[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]]])

In [29]:
s="priya" # s, string is iterable object not iterable with iter() function, next() is used to iter the iterable object
next(s)

TypeError: 'str' object is not an iterator

In [30]:
f=iter(s)

In [31]:
next(f)

'p'

In [32]:
l=[1,2,3,6,6,8,9,9]

In [33]:
i=iter(l)

In [34]:
next(i)

1

In [35]:
np.fromiter([1,2,3,4,5,],dtype=int)

array([1, 2, 3, 4, 5])

In [1]:
np.fromstring("1234/45/675/3467/2467",sep="/")

<IPython.core.display.Javascript object>

array([1234.,   45.,  675., 3467., 2467.])

In [37]:
arr

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [38]:
arr.ndim

1

In [39]:
arr.size

5

In [40]:
arr.shape

(5,)

In [41]:
arr.dtype

dtype('<U1')

In [3]:
list(range(0,4)) # integer

[0, 1, 2, 3]

In [28]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [25]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [26]:
list(range(0,5.6))

TypeError: 'float' object cannot be interpreted as an integer

In [24]:
np.arange(0,5.6)

array([0., 1., 2., 3., 4., 5.])

In [45]:
np.arange(0,6.7,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6])

In [46]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [48]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.ones(4)

array([1., 1., 1., 1.])

In [54]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
np.ones((5,2))*3 # arithmethic operation is supported

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [36]:
np.empty([3,3])

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 5.79e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [30]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
np.random.rand(2,3)

array([[0.69687793, 0.00329882, 0.88853934],
       [0.13118135, 0.78161995, 0.49641467]])

In [66]:
np.random.rand(4,5,5)

array([[[0.90794762, 0.2793176 , 0.76477721, 0.87479897, 0.68266699],
        [0.54381965, 0.48909674, 0.29196631, 0.87601719, 0.08040717],
        [0.42921852, 0.27940723, 0.58991064, 0.16100881, 0.28280513],
        [0.60494468, 0.55643574, 0.45088693, 0.5284293 , 0.41552841],
        [0.10324074, 0.00357178, 0.05802112, 0.87885141, 0.03593201]],

       [[0.4188663 , 0.94310274, 0.01713669, 0.37155931, 0.39788975],
        [0.05768547, 0.46832161, 0.07655871, 0.66685529, 0.51972354],
        [0.9910552 , 0.43904927, 0.10286704, 0.95060286, 0.95047734],
        [0.80229991, 0.44428233, 0.80776808, 0.52423162, 0.5181117 ],
        [0.17201324, 0.61265704, 0.76125346, 0.51265459, 0.83646754]],

       [[0.54238037, 0.59040039, 0.98978309, 0.48016577, 0.12088148],
        [0.09930234, 0.96631549, 0.53485084, 0.13635641, 0.22954268],
        [0.15906717, 0.06133014, 0.45041558, 0.28888141, 0.92720378],
        [0.59949981, 0.30561733, 0.21439512, 0.09356812, 0.21642964],
        [0.64757

In [38]:
np.random.rand(3,5,2)

array([[[0.39080346, 0.47322315],
        [0.49960827, 0.32370549],
        [0.0213764 , 0.7515281 ],
        [0.68278931, 0.32675552],
        [0.29514579, 0.29722367]],

       [[0.63558925, 0.69217011],
        [0.46313847, 0.67183909],
        [0.40785333, 0.71141521],
        [0.80662642, 0.03938371],
        [0.25398033, 0.27911441]],

       [[0.79088339, 0.28988222],
        [0.03984378, 0.3838236 ],
        [0.53933987, 0.26376133],
        [0.50032238, 0.08857768],
        [0.43076406, 0.11437768]]])

In [4]:
np.random.rand(4,5,3)

<IPython.core.display.Javascript object>

array([[[0.08145188, 0.37367363, 0.43232786],
        [0.26758917, 0.48144996, 0.73275794],
        [0.94147466, 0.81962355, 0.05041333],
        [0.41343467, 0.77021858, 0.21784928],
        [0.84887342, 0.69182516, 0.25724763]],

       [[0.23576213, 0.30244372, 0.08706924],
        [0.15488591, 0.50564188, 0.55086911],
        [0.82565324, 0.74661741, 0.1571559 ],
        [0.83102033, 0.18207149, 0.38792574],
        [0.04837577, 0.60489349, 0.32689312]],

       [[0.35544062, 0.16812043, 0.94543395],
        [0.96054677, 0.99911745, 0.84939704],
        [0.01095988, 0.45188417, 0.01102246],
        [0.8105081 , 0.62798169, 0.23059278],
        [0.47458042, 0.89294391, 0.17529477]],

       [[0.50618745, 0.03631486, 0.41157844],
        [0.82171108, 0.60471852, 0.03522289],
        [0.62376197, 0.9874926 , 0.721741  ],
        [0.92234268, 0.43880075, 0.08648417],
        [0.12426441, 0.78142025, 0.30861702]]])

In [68]:
np.random.randn(3,5) #randn is standard normal distribution, where mean is 0 and SD is 1

array([[-0.22207319,  0.64343796, -0.30674386,  0.69292997, -1.71551032],
       [ 0.48868162, -0.3805778 , -0.63831098,  1.40601018,  1.02646098],
       [-1.08876686,  0.20116763, -0.16786064,  2.24653781, -1.47913974]])

In [69]:
np.random.randint(2,69)

18

In [71]:
np.random.randint(3,20,size=30)

array([ 6,  5, 12,  6,  7,  3, 18,  4, 19, 10, 13, 18, 12,  9,  6,  3,  5,
       14, 10,  7, 17, 14,  8, 13, 17, 12, 17, 19, 16, 13])

In [73]:
np.random.randint(24,50, (3,5))

array([[24, 42, 28, 48, 37],
       [34, 44, 45, 31, 25],
       [38, 24, 38, 33, 34]])

In [76]:
ar1=np.random.randint(10,60, (4,5))

In [77]:
ar1

array([[48, 52, 34, 11, 27],
       [54, 42, 13, 59, 11],
       [45, 53, 42, 48, 56],
       [38, 18, 48, 40, 10]])

In [78]:
ar1.shape

(4, 5)

In [79]:
ar1.reshape(5,4)

array([[48, 52, 34, 11],
       [27, 54, 42, 13],
       [59, 11, 45, 53],
       [42, 48, 56, 38],
       [18, 48, 40, 10]])

In [80]:
ar1.reshape(20,1)

array([[48],
       [52],
       [34],
       [11],
       [27],
       [54],
       [42],
       [13],
       [59],
       [11],
       [45],
       [53],
       [42],
       [48],
       [56],
       [38],
       [18],
       [48],
       [40],
       [10]])

In [81]:
ar1.reshape(2,10)

array([[48, 52, 34, 11, 27, 54, 42, 13, 59, 11],
       [45, 53, 42, 48, 56, 38, 18, 48, 40, 10]])

In [82]:
ar1

array([[48, 52, 34, 11, 27],
       [54, 42, 13, 59, 11],
       [45, 53, 42, 48, 56],
       [38, 18, 48, 40, 10]])

In [84]:
ar1[1,2] 

13

In [85]:
ar1[1,2]=12

In [86]:
ar1

array([[48, 52, 34, 11, 27],
       [54, 42, 12, 59, 11],
       [45, 53, 42, 48, 56],
       [38, 18, 48, 40, 10]])

In [87]:
m1=np.random.randint(1,5,(3,3))

In [89]:
m1

array([[4, 2, 2],
       [4, 3, 4],
       [2, 1, 3]])

In [90]:
m2=np.random.randint(1,5,(3,3))

In [91]:
m2

array([[4, 2, 1],
       [4, 4, 3],
       [3, 3, 1]])

In [92]:
m1*m2 # element multiplication

array([[16,  4,  2],
       [16, 12, 12],
       [ 6,  3,  3]])

In [93]:
m1@m2 # matrix muplication 

array([[30, 22, 12],
       [40, 32, 17],
       [21, 17,  8]])

In [94]:
m1/0

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [95]:
m1.T

array([[4, 4, 2],
       [2, 3, 1],
       [2, 4, 3]])

In [96]:
m1

array([[4, 2, 2],
       [4, 3, 4],
       [2, 1, 3]])

In [97]:
m1.max()

4

In [98]:
m1**2

array([[16,  4,  4],
       [16,  9, 16],
       [ 4,  1,  9]], dtype=int32)

In [99]:
np.exp(m1)

array([[54.59815003,  7.3890561 ,  7.3890561 ],
       [54.59815003, 20.08553692, 54.59815003],
       [ 7.3890561 ,  2.71828183, 20.08553692]])

In [100]:
np.log10(m1)

array([[0.60205999, 0.30103   , 0.30103   ],
       [0.60205999, 0.47712125, 0.60205999],
       [0.30103   , 0.        , 0.47712125]])

In [102]:
np.sqrt(m1)

array([[2.        , 1.41421356, 1.41421356],
       [2.        , 1.73205081, 2.        ],
       [1.41421356, 1.        , 1.73205081]])

In [103]:
np.pi

3.141592653589793

In [39]:
np.random.rand(3,4,5)

array([[[0.07950999, 0.70448865, 0.64988583, 0.87413477, 0.33269694],
        [0.82364109, 0.52403861, 0.73548988, 0.28762338, 0.26594865],
        [0.47813961, 0.78648704, 0.46371751, 0.01919925, 0.48625242],
        [0.45353224, 0.85315854, 0.27338331, 0.70738666, 0.61420375]],

       [[0.98795626, 0.36795868, 0.17378848, 0.84369487, 0.10515028],
        [0.39009506, 0.52035856, 0.2187957 , 0.38238006, 0.45664146],
        [0.3515759 , 0.15840439, 0.13665603, 0.46244094, 0.19989336],
        [0.37818692, 0.03509132, 0.25038786, 0.77972932, 0.89490602]],

       [[0.32716436, 0.79284616, 0.67385978, 0.86008641, 0.95504784],
        [0.46654819, 0.8032989 , 0.62580507, 0.44914577, 0.92617074],
        [0.11399189, 0.69328882, 0.63099623, 0.6283209 , 0.48246902],
        [0.59168147, 0.5131813 , 0.67909089, 0.8683237 , 0.06869972]]])